### ISSUE TITLE
Remote image display issue & Filtering extra image formatting text

### ISSUE THREAD

**Issue by CharlesChiuGit** [sawhney17/logseq-schrodinger#20]
In Logseq:
![image](https://user-images.githubusercontent.com/32497323/165098096-23c0f243-afc8-483f-a038-2f0cbcfa1e65.png)

Exported md:

```md
Illustration of Logseq's implemented task states:

- [Discoed Link](https://discord.com/channels/725182569297215569/725182570131751005/952564162792402976)

![logseq_implemented_task_states](https://raw.githubusercontent.com/charleschiu2012/image-hosting/main/img/logseq_implemented_task_states.png){:height 290, :width 1216}

---
```

In Hugo:
![image](https://user-images.githubusercontent.com/32497323/165098350-f3939477-6403-42cf-9b20-4921eb5e351e.png)

**Comment by CharlesChiuGit** [comment]
Found the reason for remote image display issue. 
The uppercases in the link are transformed to lowercases.
For instance,
`https://raw.githubusercontent.com/charleschiu2012/image-hosting/main/img/Logseq_implemented_task_states.png`
=>
`https://raw.githubusercontent.com/charleschiu2012/image-hosting/main/img/logseq_implemented_task_states.png`

**Comment by sawhney17** [comment]
Extra formatting issue is done.
