### ISSUE TITLE
No getting the "export public pages to Hugo" 

### ISSUE THREAD

**Issue by exist2021** [sawhney17/logseq-schrodinger#25]
So I have installed the plugin but not getting an option to "export public pages to Hugo"

**Comment by exist2021** [comment]
Also, the single-page export function is buggy. Here I am at some other page and it offers to export some other page and nothing happens when I click convert. 
![Screenshot 2022-07-14 at 4 38 58 PM](https://user-images.githubusercontent.com/83490199/178969645-6eb00c3b-99ea-4ea3-b92f-e843f2378964.png)

**Comment by sawhney17** [comment]
Export public pages to Hugo is accessible via the three dots in the top right corner. This will be there provided you're in a page.

**Comment by exist2021** [comment]
Too buggy! No time to spare anymore. Appreciate the support.

**Comment by exist2021** [comment]
![Screenshot 2022-07-15 at 12 10 21 PM](https://user-images.githubusercontent.com/83490199/179172354-26a1e077-297b-4400-a43a-27e7f98dddc0.png)

![Screenshot 2022-07-15 at 12 30 23 PM](https://user-images.githubusercontent.com/83490199/179172399-28f365e0-a086-44da-b2b6-3a370e2a8b77.png)

![Screenshot 2022-07-15 at 12 49 50 PM](https://user-images.githubusercontent.com/83490199/179173244-31140ff2-6f87-45a4-bcbc-88d683329aa5.png)

![Screenshot 2022-07-15 at 12 08 20 PM](https://user-images.githubusercontent.com/83490199/179173897-7aa4d03b-c224-4e35-9e88-ab7b88c82338.png)

![Screenshot 2022-07-15 at 12 50 28 PM](https://user-images.githubusercontent.com/83490199/179173964-5af264ac-4019-4141-8f7e-f5eff5974e0d.png)



okay the above screenshots explain the following

1. Even after setting all pages to the public, my pages are still private. I made a couple of pages public individually and exported them again but still, the local host doesn't any of my blogposts
2. The empty site is loading at the local host but not on https://exist2021.github.io/articulation/

Any support would be appreciayed
