### ISSUE TITLE
I put a wiki link into my blogpost and Netlify Build failed

### ISSUE THREAD

**Issue by exist2021** [sawhney17/logseq-schrodinger#26]
Not sure why this happened. - I put a wiki link into my blogpost and Netlify Build failed 

Here is the snapshot of the error log - 
![Screenshot 2022-07-26 at 5 56 02 PM](https://user-images.githubusercontent.com/83490199/181006147-6cdffd7f-5224-44c0-8709-13c08c397d14.png)

**Comment by sawhney17** [comment]
What syntax did you use for the link?

**Comment by exist2021** [comment]
[[wikilink]]
